version: 0.2

env:
  variables:
    DOCKER_IMAGE_NAME: "110791978545.dkr.ecr.us-west-2.amazonaws.com/springboot-ushop-rest-inventory"

phases:
  install:
    commands:
    - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=vfs&
    - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
    - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email) | sed 's,https://,,g'
    - DOCKER_IMAGE_TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"  
  build:
    commands:
    - mvn clean install
    - mvn verify
  post_build:
    commands:
    # - docker build -t $DOCKER_IMAGE_NAME .
    # - docker tag $DOCKER_IMAGE_NAME $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG 
    # - docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG 
    
artifacts:
  files:
    - target/*.jar
cache:
  paths:
    - '/root/.m2/**/*'
